### ISSUE TITLE
Dead during cooldown check

### ISSUE THREAD

**Issue by danirod** [makigas/clank#159]
```
TypeError: Cannot read property 'getTime' of null
    at requiresCooldown (/clank/dist/hooks/verify.js:11:61)
    at VerifyService.handleMessage (/clank/dist/hooks/verify.js:42:13)
    at Makibot.<anonymous> (/clank/dist/hooks/verify.js:22:48)
    at Makibot.emit (events.js:327:22)
    at MessageCreateHandler.handle (/clank/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/clank/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/clank/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/clank/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/clank/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
```

**Comment by danirod** [comment]
Fixed in https://github.com/makigas/clank/commit/a931eb314035724d79cca896bacb8b5d25c8e3a4
